// products.js

const products = [
  // Mobiles
  {
    category_id: 1,
    category: 'Mobile',
    brand: 'BrandA',
    model: 'ModelX',
    price: 699,
    screen_size: '6.1 inches',
    battery: '3000 mAh',
    storage: '128 GB',
    ram: '6 GB',
    camera: '12 MP',
  },
  {
    category_id: 1,
    category: 'Mobile',
    brand: 'BrandB',
    model: 'ModelY',
    price: 799,
    screen_size: '6.5 inches',
    battery: '4000 mAh',
    storage: '256 GB',
    ram: '8 GB',
    camera: '48 MP',
  },
  {
    category_id: 1,
    category: 'Mobile',
    brand: 'BrandC',
    model: 'ModelZ',
    price: 499,
    screen_size: '5.8 inches',
    battery: '2500 mAh',
    storage: '64 GB',
    ram: '4 GB',
    camera: '16 MP',
  },
  // Laptops
  {
    category_id: 2,
    category: 'Laptop',
    brand: 'BrandD',
    model: 'LaptopA',
    price: 999,
    screen_size: '13.3 inches',
    battery: '5000 mAh',
    storage: '512 GB SSD',
    ram: '8 GB',
    processor: 'Intel i5',
    graphics: 'Intel UHD',
  },
  {
    category_id: 2,
    category: 'Laptop',
    brand: 'BrandE',
    model: 'LaptopB',
    price: 1299,
    screen_size: '15.6 inches',
    battery: '6000 mAh',
    storage: '1 TB SSD',
    ram: '16 GB',
    processor: 'Intel i7',
    graphics: 'NVIDIA GTX 1650',
  },
  {
    category_id: 2,
    category: 'Laptop',
    brand: 'BrandF',
    model: 'LaptopC',
    price: 799,
    screen_size: '14 inches',
    battery: '4500 mAh',
    storage: '256 GB SSD',
    ram: '8 GB',
    processor: 'AMD Ryzen 5',
    graphics: 'AMD Radeon Vega 8',
  },
  // Tablets
  {
    category_id: 3,
    category: 'Tablet',
    brand: 'BrandG',
    model: 'TabletA',
    price: 399,
    screen_size: '10.1 inches',
    battery: '6000 mAh',
    storage: '128 GB',
    ram: '4 GB',
    camera: '8 MP',
  },
  {
    category_id: 3,
    category: 'Tablet',
    brand: 'BrandH',
    model: 'TabletB',
    price: 499,
    screen_size: '11 inches',
    battery: '7000 mAh',
    storage: '256 GB',
    ram: '6 GB',
    camera: '12 MP',
  },
  {
    category_id: 3,
    category: 'Tablet',
    brand: 'BrandI',
    model: 'TabletC',
    price: 299,
    screen_size: '8.4 inches',
    battery: '5000 mAh',
    storage: '64 GB',
    ram: '3 GB',
    camera: '5 MP',
  },
];

export default products;
